food/urls.py
from django.urls import path
from . import views
app_name = 'food'

urlpatterns = [
    
   path('',views.IndexClassView.as_view(),name="index"),
   path('update/<int:id>/',views.update_item,name="update"),
   path('delete/<int:pk>/',views.delete_item,name="delete"),
   path('<int:pk>/',views.FoodDetail.as_view(),name="detail"),
   path('item/',views.item,name="item"),
   # add to item
   path('add/',views.CreateItem.as_view(),name="create_item"),
  
   
   
  
    
               
]

movieapi/urls.py
from django.urls import path
from .views import MovieAPIView,MovieDetail

urlpatterns = [
    path('', MovieAPIView.as_view()),
    path('<int:pk>/', MovieDetail.as_view()),
    
               
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as users_views
from django.contrib.auth import views as authentication_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movie/', include('movieapi.urls')),
    path('food/', include('food.urls')),
    path('register/',users_views.register,name="register"),
    path('login/',authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',users_views.profilepage,name='profile'),
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Item(models.Model):
    
    def __str__(self):
        return self.item_name
    user_name = models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    item_name  = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.ImageField(upload_to='Food',default="Food/None/seample.jpg")
    
    def get_absolute_url(self):
        return reverse("food:detail", kwargs={"pk": self.pk})
    

movieapi/models.py
from django.db import models

# Create your models here.

myapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    def __str__(self):
        return self.name
    image = models.ImageField(upload_to='Images',default="Images/None/seample.jpg")
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    rating = models.FloatField()

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='Pictures',default="Pictures/profile.png")
    location = models.CharField(max_length=100)
    def __str__(self):
        return self.user.username

food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields =['item_name', 'item_desc','item_price', 'item_image']
        

users/forms.py
from django import forms 

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    
    class Meta:
        model = User
        fields =['username','email','password1','password2']

food/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Item
from django.template import loader
from .forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import  CreateView

def index(request):
    item_list = Item.objects.all()
    #template=loader.get_template('food/index.html')
    context ={
        'item_list':item_list,
    }
    return render(request,'food/index.html',context)

class IndexClassView(ListView):
    model = Item
    template_name = 'food/index.html'
    context_object_name = 'item_list'
    

class FoodDetail(DetailView):
    model = Item
    template_name = 'food/detail.html'
    context_object_name = 'item'
    
def  item(request):
    return HttpResponse("This is item view")


def detail(request,item_id):
    item = Item.objects.get(pk=item_id)
    
    return render(request,'food/detail.html',{'item':item})


def create_item(request):
    form = ItemForm(request.POST or None)
    if form.is_valid():
        form.save()
        
        return redirect('food:index')
    return render(request,'food/item-form.html',{'form':form})

class CreateItem(CreateView):
    model = Item
    fields = ['item_name','item_desc', 'item_price','item_image']
    template_name = 'food/item-form.html'
    
    def form_valid(self,form):
        form.instance.user_name = self.request.user
        return super().form_valid(form)
    


def update_item(request,id):
    itemU = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=itemU)
    
    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request,'food/item-form.html',{'form':form,'itemU':itemU})


def delete_item(request,pk_item):
    item = Item.objects.get(id=pk_item)
    if request.method =='POST':
        item.delete()
        return redirect('food:index')
    return render(request,'food/delete.html',{'item':item})

movieapi/views.py
from django.shortcuts import render
from rest_framework import generics
from myapp.models import Movie
from .serializers import MovieSerializer
# Create your views here.

class MovieAPIView(generics.ListCreateAPIView):
    queryset = Movie.objects.all()
    serializer_class = MovieSerializer


class MovieDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Movie.objects.all()
    serializer_class = MovieSerializer

myapp/views.py
from django.shortcuts import render

# Create your views here.

users/views.py
from django.shortcuts import render,redirect
#from  django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import RegisterForm

# Create your views here.

def  register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f'Welcom {username} , your account is created')
            return redirect('login')
    else:
        form = RegisterForm()
            
  
    
    return render(request,'users/register.html',{'form':form}) 

@login_required
def profilepage(request):
    return render(request,'users/profile.html')

food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="{% static 'food/style.css' %}"> -->
    <title>Document</title>
</head>

<body>
    <nav class="navbar navbar-dark bg-dark ">
        <a href="#" class="navbar-brand">Food App</a>

        <div class="navbar nav">
            <a href="{% url 'food:create_item' %}" class="nav-item nav-link">Add Item</a>
            <a href="#" class="nav-item nav-link">Delete </a>
            <a href="{% url 'food:index'  %}" class="nav-item nav-link">View Item</a>
            {% if user.is_authenticated %}
                <a href="{% url 'logout' %}">Logout</a>
                <a href="{% url 'profile' %}">Profile</a>
                {% else %}
                    <a href="{% url 'login' %}">login</a>
            {% endif %}

        </div>

    </nav>
    <br>
      {% if messages %}
        {% for message in messages  %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        
        {% endfor %}
      {% endif %}
    {% block body %}
      
    {% endblock  %}

</body>

</html>

food/templates/food/delete.html
<form action="" method="post">
    {% csrf_token %}
    <h2> sur de vouloir supprimer {{ item.item_name }}</h2>
    <button type="submit">Confirm</button>
</form>

food/templates/food/detail.html
{% extends "food/base.html" %}

{% block body %}


<div class="container-fluid">
    <div class="row">
        <div class="col-md-6">
            <img class="card" height="150" width="150" src="{{object.item_image.url }}" alt="">


        </div>

        <div class="col-md-6">
          
           <h4> {{ object.item_name }}</h4>
            <p>{{ object.item_desc}}</p>
            <h5>{{ object.item_price }}</h5>
            <br>
            <a  class="btn btn-warning"  href="{% url 'food:update' item.pk %}">Update</a>
            <a  class="btn btn-danger"  href="{% url 'food:delete' item.pk %}">Delete</a>
        </div>
       
    </div>

   
</div>


{% endblock %}
   

food/templates/food/index.html
{% extends "food/base.html" %}




{% block body %}
{% for item in item_list %}
<div class="row">
    <div class="col-md-3 offset-md-2">
        <img class="card" height="80" width="80" src="{{ item.item_image.url }}" alt="">
    </div>

    <div class="col-md-4">
        
         <h3>{{ object.item_name }}</h3>
         <h5>{{ object.item_desc }}</h5>
         <h6>{{ object.item_price }}</h6>
         <h6> {{ object.user_name }}</h6>
    </div>

    <div class="col-md-2">
        <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
    </div>
</div>
   {{ item.item_name }}
{% endfor %}



{% endblock %}

food/templates/food/item-form.html
{% extends "food/base.html" %}

{% block body %}
  <div class="container">
   <div class="row">
       <div class="col-md-4 offset-md-4">
           <div class="card">
               <div class="card-header text-white bg-info">
                   <div class="card-title">
                   Add Item
                   </div>
               </div>

               <div class="card-body">
                   <form action="" method="post" enctype="multipart/form-data">

                       {% csrf_token %}
                        {{ form }}
                        <br>
                       <button type="submit" class="btn-info">Save</button>
                   </form>
               </div>
           </div>
       </div>
   </div>
  </div>
{% endblock  %}

users/templates/users/login.html
 {% extends "food/base.html" %}

 {% block body %}
   <div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Login
                    </div>
                </div>

                <div class="card-body">
                    <form action="" method="post">

                        {% csrf_token %}
                        {% for field in form  %}
                          <div class="form-group">
                            {{ field.name }}
                            <br>
                            {{ field }}
                          </div>
                        {% endfor %}
                        <button type="submit" class="btn-info">Signup</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
   </div>
 {% endblock  %}

users/templates/users/logout.html
<h1>You have been logged out </h1>

users/templates/users/profile.html
<h1>{{ user.username }}</h1>

<img  class="card" width="100" height="100"  src="{{ user.profile.image.url }}" alt="">

users/templates/users/register.html
{% extends "food/base.html" %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Register
                    </div>
                </div>
                <div class="card-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        {% for field in form  %}
                          <div class="form-group">
                            {{ field.name }}
                            <br>
                            {{ field }}
                          </div>
                        {% endfor %}
                        <button type="submit" class="btn-info">Register</button>
                    </form>
                </div>
            </div>

           
        </div>
    </div>
</div>
{% endblock %}